version: "3.1"
volumes:
  netflix-shareengine-api-data:
services:
    postfix:
      container_name: shareengine.email
      image: catatnight/postfix
      ports:
        - "25:25"
        - "587:587"
      environment:
        - MAIL_DOMAIN=netflix.crititag.com
        - SMTP_USER=${POSTFIX_USERNAME}:${POSTFIX_PASSWORD}
      volumes:
        - ./data/spool:/var/spool/postfix
        - ./data/logs:/var/log/postfix
      networks:
        - web        
        - internal
    netflix-shareengine-api:
        container_name: netflix.shareengine.api
        image: ${IMAGE}
        restart: always
        networks:
          - web
          - internal
        ports:
          - 7000:80
        volumes:
          - netflix-shareengine-api-data:/data          
        logging:
          options:
            max-size: 10m
            max-file: "3"
        environment:
            - SMTP_HOST=postfix
            - SMTP_PORT=587
            - SMTP_USERNAME=${POSTFIX_USERNAME}
            - SMTP_PASSWORD=${POSTFIX_PASSWORD}
        labels:          
          - traefik.enable=true
          - traefik.http.middlewares.netflix-shareengine-api-redirect-websecure.redirectscheme.scheme=https
          - traefik.backend=netflix-shareengine-api         
          - traefik.http.routers.netflix-shareengine-api.middlewares=netflix-shareengine-api-redirect-websecure
          - traefik.http.routers.netflix-shareengine-api.entrypoints=web
          - traefik.http.routers.netflix-shareengine-api.rule=Host(`netflix.crititag.com`)          
          - traefik.http.routers.netflix-shareengine-api-websecure.rule=Host(`netflix.crititag.com`)
          - traefik.http.routers.netflix-shareengine-api-websecure.entrypoints=websecure
          - traefik.http.routers.netflix-shareengine-api-websecure.tls.certresolver=le
          - traefik.http.routers.netflix-shareengine-api-websecure.tls=true
          - traefik.docker.network=web          
networks:
  web:
    external: true
  internal:
    external: false